-- ============================================================
--  AI STUDENT ASSISTANT – SAFE MIGRATION
--
--  HOW TO USE (same as database.sql):
--    1. Start Apache + MySQL in the XAMPP Control Panel.
--    2. Open  http://localhost/phpmyadmin
--    3. Click "Import" -> choose this file
--       (C:\xampp\htdocs\ai-chat\student_assistant_migration.sql) -> "Go".
--
--  This file is SAFE and IDEMPOTENT:
--    * It creates ONLY the new tables (courses, assignments,
--      quizzes, quiz_attempts, course_materials).
--    * It ADDS one nullable column (messages.course_id) if it is
--      missing - only once.
--    * It NEVER deletes tables, users, messages or any other data.
--    * You can import it again at any time without errors.
--
--  Existing tables (users, messages) keep working exactly as before.
-- ============================================================

USE ai_chat;

-- ------------------------------------------------------------
-- COURSES / SUBJECTS - every course belongs to one user
--   name ........ e.g. "Database Systems"
--   code ........ e.g. "DBMS301" (optional, may be empty)
--   description . free text shown on the course page
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS courses (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  user_id     INT NOT NULL,
  name        VARCHAR(150) NOT NULL,
  code        VARCHAR(30)  NOT NULL DEFAULT '',
  description TEXT         NULL,
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- COURSE MATERIALS - study files the student used with the AI
--
-- NOTE: the existing chat upload system sends files straight to
-- Gemini and NEVER stores them on the server (see api/chat.php).
-- We keep that behaviour and only remember the file METADATA,
-- so a course page can list "which material did I study with?".
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS course_materials (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  user_id    INT NOT NULL,
  course_id  INT NOT NULL,
  file_name  VARCHAR(255) NOT NULL,
  file_type  VARCHAR(120) NULL,
  file_size  INT          NOT NULL DEFAULT 0,
  note       VARCHAR(255) NULL,
  created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id)   REFERENCES users(id)   ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- ASSIGNMENTS
--   status ..... 'pending' | 'in_progress' | 'completed'
--   due_date ... a DATE (may be empty)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS assignments (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  user_id     INT NOT NULL,
  course_id   INT NOT NULL,
  title       VARCHAR(200) NOT NULL,
  description TEXT         NULL,
  due_date    DATE         NULL,
  status      VARCHAR(20)  NOT NULL DEFAULT 'pending',
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id)   REFERENCES users(id)   ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- QUIZZES - generated by Gemini and stored as JSON
--   questions ... JSON array, one object per question:
--                 { question, type, options, answer, explanation }
--   difficulty .. 'easy' | 'medium' | 'hard'
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS quizzes (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  user_id    INT NOT NULL,
  course_id  INT NOT NULL,
  title      VARCHAR(200) NOT NULL,
  difficulty VARCHAR(20)  NOT NULL DEFAULT 'medium',
  questions  LONGTEXT     NOT NULL,
  created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id)   REFERENCES users(id)   ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- QUIZ ATTEMPTS - one row per finished quiz
--   score ............ how many answers were correct
--   total_questions .. how many questions the quiz had
--   answers .......... JSON of what the student picked
--                      (so the result can be shown again later)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS quiz_attempts (
  id              INT AUTO_INCREMENT PRIMARY KEY,
  user_id         INT NOT NULL,
  quiz_id         INT NOT NULL,
  score           INT NOT NULL DEFAULT 0,
  total_questions INT NOT NULL DEFAULT 0,
  answers         TEXT NULL,
  created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- Connect the EXISTING messages table to a course (optional).
--
-- Old chat rows keep course_id = NULL and are not touched.
-- MariaDB/MySQL have no "ADD COLUMN IF NOT EXISTS", so we ask
-- information_schema first and only run the ALTER when needed.
-- (Running this more than once is harmless.)
-- ------------------------------------------------------------
SET @column_exists := (
  SELECT COUNT(*) FROM information_schema.COLUMNS
   WHERE TABLE_SCHEMA = DATABASE()
     AND TABLE_NAME   = 'messages'
     AND COLUMN_NAME  = 'course_id'
);

SET @alter_sql := IF(
  @column_exists = 0,
  'ALTER TABLE messages ADD COLUMN course_id INT NULL, ADD CONSTRAINT fk_messages_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE SET NULL',
  'SELECT ''messages.course_id already exists - nothing to do'' AS migration_note'
);

PREPARE migration_stmt FROM @alter_sql;
EXECUTE migration_stmt;
DEALLOCATE PREPARE migration_stmt;

-- Done. Existing data (users, messages, ...) is untouched.